version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт для доступа к приложению
    volumes:
      - .:/app      # Монтируем локальные файлы в контейнер
      - /app/node_modules # Исключаем node_modules из монтирования
    environment:
      - CHOKIDAR_USEPOLLING=true # Позволяет отслеживать изменения в файлах внутри контейнера
